#!/bin/bash
set -e

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
cd "$SCRIPT_DIR"

if [ -f "$SCRIPT_DIR/venv/bin/activate" ]; then
  source "$SCRIPT_DIR/venv/bin/activate"
fi

export WATCHOUT_NATIVE_THREADS="${WATCHOUT_NATIVE_THREADS:-1}"
export OMP_NUM_THREADS="$WATCHOUT_NATIVE_THREADS"
export OMP_THREAD_LIMIT="$WATCHOUT_NATIVE_THREADS"
export MKL_NUM_THREADS="$WATCHOUT_NATIVE_THREADS"
export OPENBLAS_NUM_THREADS="$WATCHOUT_NATIVE_THREADS"
export BLIS_NUM_THREADS="$WATCHOUT_NATIVE_THREADS"
export VECLIB_MAXIMUM_THREADS="$WATCHOUT_NATIVE_THREADS"
export NUMEXPR_NUM_THREADS="$WATCHOUT_NATIVE_THREADS"
export MALLOC_ARENA_MAX="1"

python3 main.py
